workflows:
  android-build:
    name: 打包安卓APP
    scripts:
      - name: 打包
        script: |
          chmod +x gradlew
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/release/*.apk
